global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ja4proxy'
    static_configs:
      - targets: ['proxy:9090']
    scrape_interval: 5s
    metrics_path: /metrics