# Grafana Datasource Provisioning
apiVersion: 1

datasources:
  - name: JA4proxy Prometheus
    type: prometheus
    access: proxy
    url: http://ja4proxy-prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 10s
      httpMethod: POST
