# Grafana Datasource Provisioning
apiVersion: 1

datasources:
  - name: Prometheus
    uid: PBFA97CFB590B2093
    type: prometheus
    access: proxy
    url: http://ja4proxy-prometheus-monitoring:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 10s
      httpMethod: POST
      exemplarTraceIdDestinations: []

  - name: Loki
    uid: ja4proxy-loki
    type: loki
    access: proxy
    url: http://ja4proxy-loki:3100
    editable: false
    jsonData:
      maxLines: 1000
